# Generated by Django 3.2.25 on 2025-04-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_profile_status'),
    ]

    operations = [
    ]
