# Generated by Django 3.2.25 on 2025-04-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_dashboard', '0002_auto_20250403_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_image',
        ),
    ]
